### ISSUE TITLE
Creating a papis library

### ISSUE THREAD

**Issue by alejandrogallo** [tpn/pdfs#4]
I'm forking your great document collection and creating a [papis](https://github.com/papis/papis) library
out of it.

Maybe you're also intersted in it, this is a teaser:
https://asciinema.org/a/kqghXwkkg7OCSQ5lF9kig3e9a

**Comment by tpn** [comment]
Hey, that's pretty neat!  I hadn't heard of papis before.

**Comment by alejandrogallo** [comment]
sure, I just wanted to make you aware of that! Have a nice one!

**Comment by tpn** [comment]
Hi @alejandrogallo, I'm interested in setting up papis support -- do you remember the commands you used to initialize/import the PDFs?

**Comment by alejandrogallo** [comment]
If you want I can create a bash script that will do this.
I would recommend just creating a folder for each document with an info file and the pdf file in it.
At first only the title of the document will be in it, but in time you can update the information of the pdfs
using the `papis update` command.

For instance you could do for a document

```
papis update --auto asm
```
and it will try to update automatically from the title etc. For some this will work, for others from a valid url should be able to
scrape information, or from a `doi` and so on. I'd be happy to assist you with it if you want.

**Comment by tpn** [comment]
Thanks @alejandrogallo (and sorry for the slow reply!), this is useful stuff.  I'll ping you if I have any more questions.  (It might be a while before I can sink some more time into this, though.)
